### ISSUE TITLE
[Support] Failed to build in ARM7 platform

### ISSUE THREAD

**Issue by AlexTraan** [llamerada-jp/libwebrtc#2]
Hi,

Thank you for interested repository.

I follow your guidance for armhf arch. I run "go run . build --arch=armhf" but it alert "go run: no go files listed"

Can you help me?

**Comment by llamerada-jp** [comment]
Hi,
That message does not output in my environment.
Please check you can run another golang program like hello world before running this project.

And need more information to reproduce your issue in my environment.
Please tell me about your environment like below.
- distribution and version of Linux
- golang version
- result of `go env`

**Comment by AlexTraan** [comment]
Hi @llamerada-jp  san,

Thank you for your feedback.

I inform to my environment first.
1> "distribution and version of Linux">>  docker image (https://github.com/alphacep/vosk-api/blob/master/travis/Dockerfile.dockcross)  kernal 5.4.0-42-generic
2> "golang version": go version go1.7.4 linux/amd64
2> "result of go env": 
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/go-1.7"
GOTOOLDIR="/usr/lib/go-1.7/pkg/tool/linux_amd64"
CC="/usr/xcc/armv7-unknown-linux-gnueabi/bin/armv7-unknown-linux-gnueabi-gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build315528546=/tmp/go-build -gno-record-gcc-switches"
CXX="/usr/xcc/armv7-unknown-linux-gnueabi/bin/armv7-unknown-linux-gnueabi-g++"
CGO_ENABLED="1"

I will check golang with simple program before running this project.

I just be an "empty paper" about golang, i wonder that i run  "go run . build --arch=armhf" at top folder of (https://github.com/llamerada-jp/libwebrtc), is this right place?

**Comment by AlexTraan** [comment]
Hi @llamerada-jp  san,

Follow "Please check you can run another golang program like hello world before running this project"
>>  I setup environment to able run hello word, then i run "go run . build --arch=armhf" again, the output log as below:

"go: downloading github.com/spf13/cobra v1.0.0
go: downloading github.com/spf13/viper v1.7.0
go: downloading github.com/magiconair/properties v1.8.1
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/spf13/afero v1.2.2
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/pelletier/go-toml v1.7.0
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading gopkg.in/ini.v1 v1.56.0
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading github.com/mitchellh/mapstructure v1.3.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading golang.org/x/sys v0.0.0-20200515095857-1151b9dac4a9
go: downloading golang.org/x/text v0.3.2
# runtime/cgo
armv7-unknown-linux-gnueabi-gcc: error: unrecognized command line option '-m64'
"
i stop at "armv7-unknown-linux-gnueabi-gcc: error: unrecognized command line option '-m64'.
My platform is ARM7, i would like to use ARM NEON as well.

would be great if you can give any advice/comment to help me?

**Comment by AlexTraan** [comment]
Hi @llamerada-jp  san,

Below is output log:
"libwebrtc$ go run . build --arch=armhf
/home/alex/workspace/libwebrtc/opt/depot_tools$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
/home/alex/workspace/libwebrtc/opt/depot_tools$ git pull
Already up-to-date.
/home/alex/workspace/libwebrtc/opt/linux_armhf/src$ git fetch origin
/home/alex/workspace/libwebrtc/opt/linux_armhf/src$ git checkout 2bcd4837dd5eeed98523344d437eb0b7e4f441ba
HEAD is now at 2bcd483... Merge to M85: Check for null before accessing SctpTransport map.
/home/alex/workspace/libwebrtc/opt/linux_armhf/src$ ./build/install-build-deps.sh --arm --no-chromeos-fonts --no-nacl --no-prompt
Running as non-root user.
You might have to enter your password one or more times for 'sudo'.

Hit:1 https://download.docker.com/linux/ubuntu bionic InRelease
Hit:2 https://packages.cloud.google.com/apt coral-edgetpu-stable InRelease 
Hit:4 https://packages.microsoft.com/repos/ms-teams stable InRelease     
Hit:5 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu xenial InRelease
Err:3 https://storage.googleapis.com/bazel-apt stable InRelease          
  The following signatures were invalid: KEYEXPIRED 1590239453  KEYEXPIRED 1590239453  KEYEXPIRED 1590239453
Hit:6 http://archive.ubuntu.com/ubuntu xenial InRelease                                       
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                      
Hit:8 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu xenial InRelease
Hit:9 http://ppa.launchpad.net/mystic-mirage/pycharm/ubuntu xenial InRelease                  
Ign:10 https://dl.bintray.com/sbt/debian  InRelease                                 
Hit:11 https://repo.skype.com/deb stable InRelease            
Get:12 https://dl.bintray.com/sbt/debian  Release [815 B]
Hit:12 https://dl.bintray.com/sbt/debian  Release                             
Get:13 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]   
Get:15 http://archive.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Fetched 325 kB in 2s (156 kB/s)    
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://storage.googleapis.com/bazel-apt stable InRelease: The following signatures were invalid: KEYEXPIRED 1590239453  KEYEXPIRED 1590239453  KEYEXPIRED 1590239453
W: Failed to fetch https://storage.googleapis.com/bazel-apt/dists/stable/InRelease  The following signatures were invalid: KEYEXPIRED 1590239453  KEYEXPIRED 1590239453  KEYEXPIRED 1590239453
W: Some index files failed to download. They have been ignored, or old ones used instead.
Building apt package list.
Skipping debugging symbols.
Including 32-bit libraries.
Including ARM cross toolchain.
Skipping NaCl, NaCl toolchain, NaCl ports dependencies.
Finding missing packages...
Packages required:  libpci3:i386 libx11-xcb1:i386 linux-libc-dev:i386 apache2-bin binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabihf binutils-mips64el-linux-gnuabi64 binutils-mipsel-linux-gnu bison bzip2 cdbs curl dbus-x11 devscripts dpkg-dev elfutils fakeroot flex g++-5-multilib g++-5-multilib-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-5-multilib-arm-linux-gnueabihf gcc-arm-linux-gnueabihf git-core gperf lib32gcc1 lib32gcc-s1 lib32stdc++6 libapache2-mod-php7.0 libappindicator3-1 libappindicator3-dev libasound2 libasound2-dev libatk1.0-0 libatspi2.0-0 libatspi2.0-dev libav-tools libbluetooth-dev libbrlapi0.6 libbrlapi-dev libbz2-1.0 libbz2-dev libc6 libc6-dev libc6-dev-armhf-cross libc6-i386 libcairo2 libcairo2-dev libcap2 libcap-dev libcups2 libcups2-dev libcurl4-gnutls-dev libdrm2 libdrm-dev libelf-dev libevdev2 libevdev-dev libexpat1 libffi6 libffi-dev libfontconfig1 libfreetype6 libgbm1 libgbm-dev libglib2.0-0 libglib2.0-dev libglu1-mesa-dev libgnome-keyring0 libgnome-keyring-dev libgtk-3-0 libgtk-3-dev libinput10 libinput-dev libjpeg-dev libkrb5-dev libnspr4 libnspr4-dev libnss3 libnss3-dev libpam0g libpam0g-dev libpango-1.0-0 libpci3 libpci-dev libpcre3 libpixman-1-0 libpng16-16 libpulse0 libpulse-dev libsctp-dev libspeechd2 libspeechd-dev libsqlite3-0 libsqlite3-dev libssl-dev libstdc++6 libudev1 libudev-dev libuuid1 libvulkan1 libvulkan-dev libwayland-egl1-mesa libwww-perl libx11-6 libx11-xcb1 libxau6 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6 libxinerama1 libxkbcommon-dev libxrandr2 libxrender1 libxslt1-dev libxss-dev libxt-dev libxtst6 libxtst-dev linux-libc-dev-armhf-cross locales openbox p7zip patch perl php7.0-cgi pkg-config python python-crypto python-dev python-numpy python-openssl python-psutil python-yaml realpath rpm ruby snapcraft subversion uuid-dev wdiff x11-utils xcompmgr xz-utils zip zlib1g

E: Unable to locate package lib32gcc-s1
The following command failed:  apt-get --just-print install libpci3:i386 libx11-xcb1:i386 linux-libc-dev:i386 apache2-bin binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabihf binutils-mips64el-linux-gnuabi64 binutils-mipsel-linux-gnu bison bzip2 cdbs curl dbus-x11 devscripts dpkg-dev elfutils fakeroot flex g++-5-multilib g++-5-multilib-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-5-multilib-arm-linux-gnueabihf gcc-arm-linux-gnueabihf git-core gperf lib32gcc1 lib32gcc-s1 lib32stdc++6 libapache2-mod-php7.0 libappindicator3-1 libappindicator3-dev libasound2 libasound2-dev libatk1.0-0 libatspi2.0-0 libatspi2.0-dev libav-tools libbluetooth-dev libbrlapi0.6 libbrlapi-dev libbz2-1.0 libbz2-dev libc6 libc6-dev libc6-dev-armhf-cross libc6-i386 libcairo2 libcairo2-dev libcap2 libcap-dev libcups2 libcups2-dev libcurl4-gnutls-dev libdrm2 libdrm-dev libelf-dev libevdev2 libevdev-dev libexpat1 libffi6 libffi-dev libfontconfig1 libfreetype6 libgbm1 libgbm-dev libglib2.0-0 libglib2.0-dev libglu1-mesa-dev libgnome-keyring0 libgnome-keyring-dev libgtk-3-0 libgtk-3-dev libinput10 libinput-dev libjpeg-dev libkrb5-dev libnspr4 libnspr4-dev libnss3 libnss3-dev libpam0g libpam0g-dev libpango-1.0-0 libpci3 libpci-dev libpcre3 libpixman-1-0 libpng16-16 libpulse0 libpulse-dev libsctp-dev libspeechd2 libspeechd-dev libsqlite3-0 libsqlite3-dev libssl-dev libstdc++6 libudev1 libudev-dev libuuid1 libvulkan1 libvulkan-dev libwayland-egl1-mesa libwww-perl libx11-6 libx11-xcb1 libxau6 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6 libxinerama1 libxkbcommon-dev libxrandr2 libxrender1 libxslt1-dev libxss-dev libxt-dev libxtst6 libxtst-dev linux-libc-dev-armhf-cross locales openbox p7zip patch perl php7.0-cgi pkg-config python python-crypto python-dev python-numpy python-openssl python-psutil python-yaml realpath rpm ruby snapcraft subversion uuid-dev wdiff x11-utils xcompmgr xz-utils zip zlib1g

It produced the following output:
NOTE: This is only a simulation!
      apt-get needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists...
Building dependency tree...
Reading state information...

You will have to install the above packages yourself.

exit status 1
"

do you have any comment for me?

**Comment by llamerada-jp** [comment]
Hi, @AlexTraan 

Please exec `go build . <options...>` on amd64 environment instead of on arm docker image.
Build programs can't run on arm environment.
And update your golang version if you can. Because I use golang v1.13 or higher normally, so I didn't try it on v1.7.

If you don't have any particular reason, you can use the pre-built files on the release page.
This build programs try to build the library using the last stable source code automatically and need a configurations file at `libwbrtc/configs` for the last version. I didn't try to build it with chromium m85. I didn't make the latest configuration file yet. It will take some time.

**Comment by AlexTraan** [comment]
Hi @llamerada-jp san,

"Please exec go build . <options...> on amd64 environment instead of on arm docker image."
-> yes, I execute "go build . <options...>" on amd64 environment 

"And update your golang version if you can. Because I use golang v1.13 or higher normally, so I didn't try it on v1.7."
-> sure

"If you don't have any particular reason, you can use the pre-built files on the release page.
This build programs try to build the library using the last stable source code automatically and need a configurations file at libwbrtc/configs for the last version. I didn't try to build it with chromium m85. I didn't make the latest configuration file yet. It will take some time."
-> Do your pre-build files active ARM NEON for ARM7 platform?

In your pre-build package, i don't see header for audio processing module like VAD (in common_audio folder),... How can i active it (VAD, ...) for use?

Thanks you

**Comment by AlexTraan** [comment]
Hi @llamerada-jp san,

I can be build to generate static library for now. But as mention above, in include header file, i dont see many header related to audio process part like VAD, AGC, ... Can you help to guide me how to add it in build system?

**Comment by llamerada-jp** [comment]
Hi, @AlexTraan 

Sorry, my build script does not support the multimedia feature of WebRTC.
(I must write this issue on README.md)
I don't have some knowledge and a plan to support the multimedia feature.

Instead of this project, I suggest you investigate some projects below.
- https://github.com/shiguredo-webrtc-build/webrtc-build
- https://github.com/shiguredo/momo

`momo` uses `webrtc-build`'s library file and it uses a hardware encoder on the Raspberry Pi.
I don't know if NEON is supported. But, I guess `webrtc-build` is more match than this project for your use-case.

**Comment by AlexTraan** [comment]
Hi @llamerada-jp san,

Thank you for your information.

I got it
