### ISSUE TITLE
hot to build android so file?

### ISSUE THREAD

**Issue by seamanm** [llamerada-jp/libwebrtc#6]
Hello, if I want to try this script to compile Android native library, do you have any examples I can refer to?

**Comment by llamerada-jp** [comment]
Sorry, I never tried to build libwebrtc for Android. So don't have the knowledge.
The official documentation has instructions on how to build libraries for Android. And I think it's worth a try because there is the NDK keyword.
https://webrtc.github.io/webrtc-org/native-code/android/
